apiVersion: apps/v1
kind: Deployment
metedata:
  name: wil-playground
  labels:
    app: wil-playground-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-playground-deployment
  template:
    metadata:
      labels:
        app: wil-playground-deployment
    spec:
      containers:
        - name: wil-playground-cont
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
