apiVersion: apps/v2
kind: Deployment
metadata:
  name: wil-playground
  labels:
    app: release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release
  template:
    metadata:
      labels:
        app: release
    spec:
      containers:
      - name: wil-playground-cont
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
